kind: DeploymentConfig
apiVersion: v1
metadata:
  name: iot-gc
  labels:
    app: iot-gc
    deploymentconfig: iot-gc
spec:
  replicas: 1
  selector:
    app: iot-gc
    deploymentconfig: iot-gc
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - operator
        from:
          kind: ImageStreamTag
          name: iot-gc:latest
  template:
    metadata:
      labels:
        app: iot-gc
        deploymentconfig: iot-gc
    spec:
      containers:
      - name: operator
        image: iot-gc
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            memory: 512Mi
        ports:
        volumeMounts:
      volumes:

